apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: llmops-apikeys-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "litellm.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: llmops-apikeys-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: llmops/apikeys
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
