apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: llmops-apikeys-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "litellm.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: llmops-apikeys-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        ANTHROPIC_API_KEY: '{{ "{{ .ANTHROPIC_API_KEY }}" }}'
        GEMINI_API_KEY: '{{ "{{ .GEMINI_API_KEY }}" }}'
        LANGFUSE_PUBLIC_KEY: '{{ "{{ .LANGFUSE_PUBLIC_KEY }}" }}'
        LANGFUSE_SECRET_KEY: '{{ "{{ .LANGFUSE_SECRET_KEY }}" }}'
        LITELLM_MASTER_KEY: '{{ "{{ .LITELLM_MASTER_KEY }}" }}'
        LITELLM_SALT_KEY: '{{ "{{ .LITELLM_SALT_KEY }}" }}'
        OPENAI_API_KEY: '{{ "{{ .OPENAI_API_KEY }}" }}'
        REDIS_PASSWORD: '{{ "{{ .REDIS_PASSWORD }}" }}'
        WEBUI_SECRET_KEY: '{{ "{{ .WEBUI_SECRET_KEY }}" }}'
  dataFrom:
    - extract:
        key: llmops/apikeys
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: llmops-supabase-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "litellm.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: llmops-supabase-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        LITELLM_DB_URL: '{{ "{{ .LITELLM_DB_URL }}" }}'
  dataFrom:
    - extract:
        key: llmops/supabase
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
