apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: llmops-apikeys-secret
  namespace: langfuse
  labels:
    app.kubernetes.io/part-of: llmops-platform
    app.kubernetes.io/component: secrets
    app.kubernetes.io/managed-by: ExternalSecretsOperator
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: llmops-apikeys-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
  dataFrom:
    - extract:
        key: llmops/apikeys
